package com.neusoft.ssmpro.mapper;

import com.neusoft.ssmpro.entity.CategoryPoint;
import java.util.List;

public interface CategoryPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_point
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer categorypointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_point
     *
     * @mbggenerated
     */
    int insert(CategoryPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_point
     *
     * @mbggenerated
     */
    CategoryPoint selectByPrimaryKey(Integer categorypointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_point
     *
     * @mbggenerated
     */
    List<CategoryPoint> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_point
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CategoryPoint record);
}