package com.neusoft.ssmpro.mapper;

import com.neusoft.ssmpro.entity.CategoryV;
import java.util.List;

public interface CategoryVMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_v
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer categoryvId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_v
     *
     * @mbggenerated
     */
    int insert(CategoryV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_v
     *
     * @mbggenerated
     */
    CategoryV selectByPrimaryKey(Integer categoryvId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_v
     *
     * @mbggenerated
     */
    List<CategoryV> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_v
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CategoryV record);
    
    
    List<CategoryV> loadCategoryVByNavId(Integer cateNavId);
    
    List<Integer> loadFirstNavVIds();
    
}