package com.neusoft.ssmpro.mapper;

import com.neusoft.ssmpro.entity.CommentContent;
import java.util.List;

public interface CommentContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_comment_content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer commentContentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_comment_content
     *
     * @mbggenerated
     */
    int insert(CommentContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_comment_content
     *
     * @mbggenerated
     */
    CommentContent selectByPrimaryKey(Integer commentContentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_comment_content
     *
     * @mbggenerated
     */
    List<CommentContent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_comment_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommentContent record);
}