package com.neusoft.ssmpro.mapper;

import com.neusoft.ssmpro.entity.Mark;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_mark
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer markId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_mark
     *
     * @mbggenerated
     */
    int insert(Mark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_mark
     *
     * @mbggenerated
     */
    Mark selectByPrimaryKey(Integer markId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_mark
     *
     * @mbggenerated
     */
    List<Mark> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_mark
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Mark record);
    
    List<Mark> loadByBlogId(Long blodId);
    
    
    List<Mark> ListAllMark();

	boolean addMark(Mark mark);

	boolean switchstatus(Mark mark);

	void insertMarkBlog(@Param("markId")Integer id, @Param("blogId")Long blogId);
}