package com.neusoft.ssmpro.mapper;

import com.neusoft.ssmpro.entity.Read;
import java.util.List;

public interface ReadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_read
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long readId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_read
     *
     * @mbggenerated
     */
    int insert(Read record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_read
     *
     * @mbggenerated
     */
    Read selectByPrimaryKey(Long readId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_read
     *
     * @mbggenerated
     */
    List<Read> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_read
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Read record);
}