package com.neusoft.ssmpro.mapper;

import com.neusoft.ssmpro.entity.tblUser;
import java.util.List;

public interface tblUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated
     */
    int insert(tblUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated
     */
    tblUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated
     */
    List<tblUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(tblUser record);

	tblUser getUserByName(String username);
	
	int addUser(tblUser user);
	
	/**
	 * 
	 * @Title: checkByUserName 
	 * @Description: 判断用户名是否存在  true代表可用 false代表不可用
	 * @param userName
	 * @return
	 * @return: boolean
	 */
	int checkByUserName(String userName);

	
	int checkOldPwd(tblUser user);
	
	int changePwd(tblUser user);
}