package com.neusoft.ssmpro.entity;

import java.io.Serializable;
import java.util.Date;

public class CategoryNav implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_nav.categorynav_id
     *
     * @mbggenerated
     */
    private Integer categorynavId;

    @Override
	public String toString() {
		return "CategoryNav [categorynavId=" + categorynavId + ", categorynavNo=" + categorynavNo + ", categorynavName="
				+ categorynavName + ", categorynavStatus=" + categorynavStatus + ", categorynavCtime="
				+ categorynavCtime + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_nav.categorynav_no
     *
     * @mbggenerated
     */
    private Integer categorynavNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_nav.categorynav_name
     *
     * @mbggenerated
     */
    private String categorynavName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_nav.categorynav_status
     *
     * @mbggenerated
     */
    private String categorynavStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_nav.categorynav_ctime
     *
     * @mbggenerated
     */
    private Date categorynavCtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_nav.categorynav_id
     *
     * @return the value of tbl_category_nav.categorynav_id
     *
     * @mbggenerated
     */
    public Integer getCategorynavId() {
        return categorynavId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_nav.categorynav_id
     *
     * @param categorynavId the value for tbl_category_nav.categorynav_id
     *
     * @mbggenerated
     */
    public void setCategorynavId(Integer categorynavId) {
        this.categorynavId = categorynavId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_nav.categorynav_no
     *
     * @return the value of tbl_category_nav.categorynav_no
     *
     * @mbggenerated
     */
    public Integer getCategorynavNo() {
        return categorynavNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_nav.categorynav_no
     *
     * @param categorynavNo the value for tbl_category_nav.categorynav_no
     *
     * @mbggenerated
     */
    public void setCategorynavNo(Integer categorynavNo) {
        this.categorynavNo = categorynavNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_nav.categorynav_name
     *
     * @return the value of tbl_category_nav.categorynav_name
     *
     * @mbggenerated
     */
    public String getCategorynavName() {
        return categorynavName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_nav.categorynav_name
     *
     * @param categorynavName the value for tbl_category_nav.categorynav_name
     *
     * @mbggenerated
     */
    public void setCategorynavName(String categorynavName) {
        this.categorynavName = categorynavName == null ? null : categorynavName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_nav.categorynav_status
     *
     * @return the value of tbl_category_nav.categorynav_status
     *
     * @mbggenerated
     */
    public String getCategorynavStatus() {
        return categorynavStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_nav.categorynav_status
     *
     * @param categorynavStatus the value for tbl_category_nav.categorynav_status
     *
     * @mbggenerated
     */
    public void setCategorynavStatus(String categorynavStatus) {
        this.categorynavStatus = categorynavStatus == null ? null : categorynavStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_nav.categorynav_ctime
     *
     * @return the value of tbl_category_nav.categorynav_ctime
     *
     * @mbggenerated
     */
    public Date getCategorynavCtime() {
        return categorynavCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_nav.categorynav_ctime
     *
     * @param categorynavCtime the value for tbl_category_nav.categorynav_ctime
     *
     * @mbggenerated
     */
    public void setCategorynavCtime(Date categorynavCtime) {
        this.categorynavCtime = categorynavCtime;
    }
}