package com.neusoft.ssmpro.entity;

import java.util.Date;

public class CommentContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_comment_content.comment_content_id
     *
     * @mbggenerated
     */
    private Integer commentContentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_comment_content.commentid
     *
     * @mbggenerated
     */
    private Integer commentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_comment_content.comment_content_question
     *
     * @mbggenerated
     */
    private String commentContentQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_comment_content.comment_content_answer
     *
     * @mbggenerated
     */
    private String commentContentAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_comment_content.comment_content_ctime
     *
     * @mbggenerated
     */
    private Date commentContentCtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_comment_content.comment_content_id
     *
     * @return the value of tbl_comment_content.comment_content_id
     *
     * @mbggenerated
     */
    public Integer getCommentContentId() {
        return commentContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_comment_content.comment_content_id
     *
     * @param commentContentId the value for tbl_comment_content.comment_content_id
     *
     * @mbggenerated
     */
    public void setCommentContentId(Integer commentContentId) {
        this.commentContentId = commentContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_comment_content.commentid
     *
     * @return the value of tbl_comment_content.commentid
     *
     * @mbggenerated
     */
    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_comment_content.commentid
     *
     * @param commentid the value for tbl_comment_content.commentid
     *
     * @mbggenerated
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_comment_content.comment_content_question
     *
     * @return the value of tbl_comment_content.comment_content_question
     *
     * @mbggenerated
     */
    public String getCommentContentQuestion() {
        return commentContentQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_comment_content.comment_content_question
     *
     * @param commentContentQuestion the value for tbl_comment_content.comment_content_question
     *
     * @mbggenerated
     */
    public void setCommentContentQuestion(String commentContentQuestion) {
        this.commentContentQuestion = commentContentQuestion == null ? null : commentContentQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_comment_content.comment_content_answer
     *
     * @return the value of tbl_comment_content.comment_content_answer
     *
     * @mbggenerated
     */
    public String getCommentContentAnswer() {
        return commentContentAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_comment_content.comment_content_answer
     *
     * @param commentContentAnswer the value for tbl_comment_content.comment_content_answer
     *
     * @mbggenerated
     */
    public void setCommentContentAnswer(String commentContentAnswer) {
        this.commentContentAnswer = commentContentAnswer == null ? null : commentContentAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_comment_content.comment_content_ctime
     *
     * @return the value of tbl_comment_content.comment_content_ctime
     *
     * @mbggenerated
     */
    public Date getCommentContentCtime() {
        return commentContentCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_comment_content.comment_content_ctime
     *
     * @param commentContentCtime the value for tbl_comment_content.comment_content_ctime
     *
     * @mbggenerated
     */
    public void setCommentContentCtime(Date commentContentCtime) {
        this.commentContentCtime = commentContentCtime;
    }
}