package com.neusoft.ssmpro.entity;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_comment.comment_id
     *
     * @mbggenerated
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_comment.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_comment.blogid
     *
     * @mbggenerated
     */
    private Integer blogid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_comment.comment_ctime
     *
     * @mbggenerated
     */
    private Date commentCtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_comment.comment_id
     *
     * @return the value of tbl_comment.comment_id
     *
     * @mbggenerated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_comment.comment_id
     *
     * @param commentId the value for tbl_comment.comment_id
     *
     * @mbggenerated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_comment.username
     *
     * @return the value of tbl_comment.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_comment.username
     *
     * @param username the value for tbl_comment.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_comment.blogid
     *
     * @return the value of tbl_comment.blogid
     *
     * @mbggenerated
     */
    public Integer getBlogid() {
        return blogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_comment.blogid
     *
     * @param blogid the value for tbl_comment.blogid
     *
     * @mbggenerated
     */
    public void setBlogid(Integer blogid) {
        this.blogid = blogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_comment.comment_ctime
     *
     * @return the value of tbl_comment.comment_ctime
     *
     * @mbggenerated
     */
    public Date getCommentCtime() {
        return commentCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_comment.comment_ctime
     *
     * @param commentCtime the value for tbl_comment.comment_ctime
     *
     * @mbggenerated
     */
    public void setCommentCtime(Date commentCtime) {
        this.commentCtime = commentCtime;
    }
}