package com.neusoft.ssmpro.entity;

import java.io.Serializable;
import java.util.Date;

public class Global implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_global.global_id
     *
     * @mbggenerated
     */
    private Integer globalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_global.global_htitle
     *
     * @mbggenerated
     */
    private String globalHtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_global.global_footertext
     *
     * @mbggenerated
     */
    private String globalFootertext;

    @Override
	public String toString() {
		return "Global [globalId=" + globalId + ", globalHtitle=" + globalHtitle + ", globalFootertext="
				+ globalFootertext + ", globalAttentiontitle=" + globalAttentiontitle + ", globalRecommendtitle="
				+ globalRecommendtitle + ", globalCategorytitle=" + globalCategorytitle + ", globalCommenttitle="
				+ globalCommenttitle + ", globalCtime=" + globalCtime + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_global.global_attentiontitle
     *
     * @mbggenerated
     */
    private String globalAttentiontitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_global.global_recommendtitle
     *
     * @mbggenerated
     */
    private String globalRecommendtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_global.global_categorytitle
     *
     * @mbggenerated
     */
    private String globalCategorytitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_global.global_commenttitle
     *
     * @mbggenerated
     */
    private String globalCommenttitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_global.global_ctime
     *
     * @mbggenerated
     */
    private Date globalCtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_global.global_id
     *
     * @return the value of tbl_global.global_id
     *
     * @mbggenerated
     */
    public Integer getGlobalId() {
        return globalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_global.global_id
     *
     * @param globalId the value for tbl_global.global_id
     *
     * @mbggenerated
     */
    public void setGlobalId(Integer globalId) {
        this.globalId = globalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_global.global_htitle
     *
     * @return the value of tbl_global.global_htitle
     *
     * @mbggenerated
     */
    public String getGlobalHtitle() {
        return globalHtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_global.global_htitle
     *
     * @param globalHtitle the value for tbl_global.global_htitle
     *
     * @mbggenerated
     */
    public void setGlobalHtitle(String globalHtitle) {
        this.globalHtitle = globalHtitle == null ? null : globalHtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_global.global_footertext
     *
     * @return the value of tbl_global.global_footertext
     *
     * @mbggenerated
     */
    public String getGlobalFootertext() {
        return globalFootertext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_global.global_footertext
     *
     * @param globalFootertext the value for tbl_global.global_footertext
     *
     * @mbggenerated
     */
    public void setGlobalFootertext(String globalFootertext) {
        this.globalFootertext = globalFootertext == null ? null : globalFootertext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_global.global_attentiontitle
     *
     * @return the value of tbl_global.global_attentiontitle
     *
     * @mbggenerated
     */
    public String getGlobalAttentiontitle() {
        return globalAttentiontitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_global.global_attentiontitle
     *
     * @param globalAttentiontitle the value for tbl_global.global_attentiontitle
     *
     * @mbggenerated
     */
    public void setGlobalAttentiontitle(String globalAttentiontitle) {
        this.globalAttentiontitle = globalAttentiontitle == null ? null : globalAttentiontitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_global.global_recommendtitle
     *
     * @return the value of tbl_global.global_recommendtitle
     *
     * @mbggenerated
     */
    public String getGlobalRecommendtitle() {
        return globalRecommendtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_global.global_recommendtitle
     *
     * @param globalRecommendtitle the value for tbl_global.global_recommendtitle
     *
     * @mbggenerated
     */
    public void setGlobalRecommendtitle(String globalRecommendtitle) {
        this.globalRecommendtitle = globalRecommendtitle == null ? null : globalRecommendtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_global.global_categorytitle
     *
     * @return the value of tbl_global.global_categorytitle
     *
     * @mbggenerated
     */
    public String getGlobalCategorytitle() {
        return globalCategorytitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_global.global_categorytitle
     *
     * @param globalCategorytitle the value for tbl_global.global_categorytitle
     *
     * @mbggenerated
     */
    public void setGlobalCategorytitle(String globalCategorytitle) {
        this.globalCategorytitle = globalCategorytitle == null ? null : globalCategorytitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_global.global_commenttitle
     *
     * @return the value of tbl_global.global_commenttitle
     *
     * @mbggenerated
     */
    public String getGlobalCommenttitle() {
        return globalCommenttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_global.global_commenttitle
     *
     * @param globalCommenttitle the value for tbl_global.global_commenttitle
     *
     * @mbggenerated
     */
    public void setGlobalCommenttitle(String globalCommenttitle) {
        this.globalCommenttitle = globalCommenttitle == null ? null : globalCommenttitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_global.global_ctime
     *
     * @return the value of tbl_global.global_ctime
     *
     * @mbggenerated
     */
    public Date getGlobalCtime() {
        return globalCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_global.global_ctime
     *
     * @param globalCtime the value for tbl_global.global_ctime
     *
     * @mbggenerated
     */
    public void setGlobalCtime(Date globalCtime) {
        this.globalCtime = globalCtime;
    }
}