package com.neusoft.ssmpro.entity;

import java.util.Date;

public class Read {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_read.read_id
     *
     * @mbggenerated
     */
    private Long readId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_read.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_read.blogid
     *
     * @mbggenerated
     */
    private Integer blogid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_read.read_ctime
     *
     * @mbggenerated
     */
    private Date readCtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_read.read_id
     *
     * @return the value of tbl_read.read_id
     *
     * @mbggenerated
     */
    public Long getReadId() {
        return readId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_read.read_id
     *
     * @param readId the value for tbl_read.read_id
     *
     * @mbggenerated
     */
    public void setReadId(Long readId) {
        this.readId = readId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_read.userid
     *
     * @return the value of tbl_read.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_read.userid
     *
     * @param userid the value for tbl_read.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_read.blogid
     *
     * @return the value of tbl_read.blogid
     *
     * @mbggenerated
     */
    public Integer getBlogid() {
        return blogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_read.blogid
     *
     * @param blogid the value for tbl_read.blogid
     *
     * @mbggenerated
     */
    public void setBlogid(Integer blogid) {
        this.blogid = blogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_read.read_ctime
     *
     * @return the value of tbl_read.read_ctime
     *
     * @mbggenerated
     */
    public Date getReadCtime() {
        return readCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_read.read_ctime
     *
     * @param readCtime the value for tbl_read.read_ctime
     *
     * @mbggenerated
     */
    public void setReadCtime(Date readCtime) {
        this.readCtime = readCtime;
    }
}