package com.neusoft.ssmpro.entity;

import java.util.Date;

public class TblRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role.role_no
     *
     * @mbggenerated
     */
    private Integer roleNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role.role_ctime
     *
     * @mbggenerated
     */
    private Date roleCtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role.id
     *
     * @return the value of tbl_role.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role.id
     *
     * @param id the value for tbl_role.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role.role_name
     *
     * @return the value of tbl_role.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role.role_name
     *
     * @param roleName the value for tbl_role.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role.role_no
     *
     * @return the value of tbl_role.role_no
     *
     * @mbggenerated
     */
    public Integer getRoleNo() {
        return roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role.role_no
     *
     * @param roleNo the value for tbl_role.role_no
     *
     * @mbggenerated
     */
    public void setRoleNo(Integer roleNo) {
        this.roleNo = roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role.role_ctime
     *
     * @return the value of tbl_role.role_ctime
     *
     * @mbggenerated
     */
    public Date getRoleCtime() {
        return roleCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role.role_ctime
     *
     * @param roleCtime the value for tbl_role.role_ctime
     *
     * @mbggenerated
     */
    public void setRoleCtime(Date roleCtime) {
        this.roleCtime = roleCtime;
    }
}